repo: http://github.com/croteb/test-cd
services:
  - frontend:
      install_script:
        - npm install .
      test_script:
        - npm test
      language: nodejs
      nodejs:
        - 0.10
        - 0.11
      propeller:
        ports:
          FRONTEND_HTTP: 8000 
          MYSQL: 3306
        services:
          - postgres
      herokudpl:
        api_key: enc:GGoKv8rMo/vntT+n03j3l5ggvVD9hVfR7UlZ8nruzbLLfA2wKKNJ7lpMNE2w\nXJC2eQ+hZBRiCJzMnaL3QPth3IVILVqY2aIoVKVMNJi3FrLeB3NyN8M6GfFy\nbklqBsQI9HNO3irqQhhHetJyAQnjfdbZMLaUhlh2+vPD17jW5QgFpFHJASoM\nzXla7MYMLlWShBOYRdlOKqsdqU7cO4/JGp/KCqQa+WLMpbzBQJ69/AmwdxP4\ndgjzAFHx+HQ70GvYWQxUkmy9dERcgV/HmUWka9kc7upuDPhvOF16EwgOKdWT\niT0BRM5PzQzU3/eFSu6S4qd8jVKqYvtfl0BrCPezFg==
        app: foaming-horse
        strategy: git
      openshiftdpl:
        user: crobe03@ca.com 
        password: enc:QB023AdBygSCegpG2t8M06FpB3YnEUfQTR1iXt6c3IxNdUhTrp1gREjBLCX0\nketY6HFPD8uVV9d1UrWEgd8eilHvSjz+zsbxNrCuLdEyc/KOWmVtxW8R8iao\n0q0enq/TPvh+DX+29QEi+e9TG0FzJNF0FGjEanMd03ycOYkrSV5j4cNE/26r\ndcTDqSqynPtL3yl5BymUsjsPJQWV5Rn14pddPXn2FtZ6FvY4LsMJ3h0gnXU/\nxn5P9VwJGtLpt/t4jfJERAlhfjHmqb4iL1FFocAqwTA3hFo989TR+puyx4N8\noQY2SjkD5ftD5NzBCik/SoV02TilnzJXnmYg71GKpg==
        domain: crobe03 
        app: thai         
  - backend:
      language: nodejs
      propeller:
        instances: 1
      herokudpl:
        api_key: enc:GGoKv8rMo/vntT+n03j3l5ggvVD9hVfR7UlZ8nruzbLLfA2wKKNJ7lpMNE2w\nXJC2eQ+hZBRiCJzMnaL3QPth3IVILVqY2aIoVKVMNJi3FrLeB3NyN8M6GfFy\nbklqBsQI9HNO3irqQhhHetJyAQnjfdbZMLaUhlh2+vPD17jW5QgFpFHJASoM\nzXla7MYMLlWShBOYRdlOKqsdqU7cO4/JGp/KCqQa+WLMpbzBQJ69/AmwdxP4\ndgjzAFHx+HQ70GvYWQxUkmy9dERcgV/HmUWka9kc7upuDPhvOF16EwgOKdWT\niT0BRM5PzQzU3/eFSu6S4qd8jVKqYvtfl0BrCPezFg==
        app: bouncing-horse
        strategy: git
      openshiftdpl:
        user: crobe03@ca.com 
        password: enc:QB023AdBygSCegpG2t8M06FpB3YnEUfQTR1iXt6c3IxNdUhTrp1gREjBLCX0\nketY6HFPD8uVV9d1UrWEgd8eilHvSjz+zsbxNrCuLdEyc/KOWmVtxW8R8iao\n0q0enq/TPvh+DX+29QEi+e9TG0FzJNF0FGjEanMd03ycOYkrSV5j4cNE/26r\ndcTDqSqynPtL3yl5BymUsjsPJQWV5Rn14pddPXn2FtZ6FvY4LsMJ3h0gnXU/\nxn5P9VwJGtLpt/t4jfJERAlhfjHmqb4iL1FFocAqwTA3hFo989TR+puyx4N8\noQY2SjkD5ftD5NzBCik/SoV02TilnzJXnmYg71GKpg==
        domain: crobe03 
        app: chi        

